version: "3.7"

services:
  database_ignite:
    restart: always
    ports:
      - 5432:5432
    image: postgres
    container_name: database_ignite
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    ports:
      - 3333:3333
    container_name: cars-api
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
